feat: fail

diff --git a/.github/workflows/masterCI.yml b/.github/workflows/masterCI.yml
--- a/.github/workflows/masterCI.yml
+++ b/.github/workflows/masterCI.yml
@@ -72,6 +72,11 @@ jobs:
     needs: fake-build
     runs-on: ubuntu-latest
     steps:
+      - name: Fake Error Step
+        run: |
+          echo "This step will fail..."
+          exit 1
+
       - name: Fake ESLint
         run: |
           echo "Starting fake ESLint..."
