feat: :zap: new tests

diff --git a/.github/workflows/masterCI.yml b/.github/workflows/masterCI.yml
--- a/.github/workflows/masterCI.yml
+++ b/.github/workflows/masterCI.yml
@@ -1,50 +1,65 @@
-name: CI/CD Pipeline
+name: CI Pipeline
 
 on:
-  push:
-    branches:
-      - main
   pull_request:
     branches:
-      - main
+      - master
 
 jobs:
-  build:
+  fake-build:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-        with:
-          ref: ${{ github.event.pull_request.head.sha }}
+      - name: Fake Build
+        run: echo "Building project..."
 
-      - name: Get commit and PR info
-        run: |
-          echo "PR Title: ${{ github.event.pull_request.title }}"
-          echo "PR Number: ${{ github.event.pull_request.number }}"
-          echo "Commit SHA of PR: ${{ github.event.pull_request.head.sha }}"
-          echo "Commit SHA of base (main): ${{ github.event.pull_request.base.sha }}"
-          echo "Branch name of PR: ${{ github.event.pull_request.head.ref }}"
-      
-      - name: Get commit details from PR
-        run: |
-          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
-            https://api.github.com/repos/${{ github.repository }}/commits/${{ github.event.pull_request.head.sha }} \
-            | jq '.commit'
-        
-      - name: Check if this is a pull request or a commit
-        id: check_pr
-        run: echo ${{ github.event_name }}
+  service-flow:
+    needs: fake-build
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        service:
+          [
+            service1,
+            service2,
+            service3,
+            service4,
+            service5,
+            service6,
+            service7,
+            service8,
+          ]
+    steps:
+      - name: Fake Connection VPN
+        run: echo "Connecting to VPN for ${{ matrix.service }}..."
 
-  # trigger:
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - name: Dispatch event to trigger Build
-  #       run: |
-  #           build_type=$(if [ "${{ github.event_name }}" == "pull_request" ]; then echo "pull_request"; else echo "other"; fi)
-  #           pull_request_number=$(if [ "${{ github.event_name }}" == "pull_request" ]; then echo "${{github.event.pull_request.number}}"; else echo ""; fi)
-  #           echo "Event Type: $build_type"
-  #           curl -X POST \
-  #           -H "Authorization: token ${{ secrets.PERSONAL_TOKEN }}" \
-  #           -H "Accept: application/vnd.github.v3+json" \
-  #           https://api.github.com/repos/${{ github.repository }}/dispatches \
-  #           -d '{"event_type":"trigger_build", "client_payload": {"buildType": "'"$build_type"'", "pull_request_number": "'"$pull_request_number"'"}}'
+      - name: Fake Run Tests
+        run: echo "Running tests for ${{ matrix.service }}..."
+
+      - name: Fake Error Step
+        if: matrix.service == 'service1' || matrix.service == 'service2'
+        run: |
+          echo "This step will fail..."
+          exit 1
+
+      - name: Fake Nomad
+        run: echo "Running Nomad for ${{ matrix.service }}..."
+
+  fake-terraform:
+    needs: fake-build
+    runs-on: ubuntu-latest
+    steps:
+      - name: Fake Terraform
+        run: |
+          echo "Starting fake terraform..."
+          sleep 45
+          echo "Fake terraform completed."
+
+  fake-eslint:
+    needs: fake-build
+    runs-on: ubuntu-latest
+    steps:
+      - name: Fake ESLint
+        run: |
+          echo "Starting fake ESLint..."
+          sleep 45
+          echo "Fake ESLint completed."
